#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

if [ -z $WIRELESS_INTERFACE ]; then
	WIRELESS_INTERFACE=wlan0
fi

if [ -z $ESSID_LIST ]; then
	ESSID_LIST=/etc/essids
fi

if [ -z $WPA_SUPPLICANT_CONF ]; then
	WPA_SUPPLICANT_CONF=/etc/wpa_supplicant.conf
fi

IFCONFIG="/sbin/ifconfig $WIRELESS_INTERFACE"
IWLIST="/usr/sbin/iwlist $WIRELESS_INTERFACE"
IWCONFIG="/usr/sbin/iwconfig $WIRELESS_INTERFACE"
WPA_SUPPLICANT_PIDFILE="/var/run/wpa_supplicant-$WIRELESS_INTERFACE.pid"
DHCPCD_PIDFILE="/var/run/dhcpcd-$WIRELESS_INTERFACE.pid"

WPA_SUPPLICANT="/usr/sbin/wpa_supplicant -B -i $WIRELESS_INTERFACE -c $WPA_SUPPLICANT_CONF -P $WPA_SUPPLICANT_PIDFILE"
DHCPCD="/usr/sbin/dhcpcd $WIRELESS_INTERFACE"

case "$1" in
	start)

		if [ $($IFCONFIG 2> /dev/null | grep inet | wc -l) -ne 0 ] ; then
			echo "Wireless Network is already running. Try 'wireless restart'"
			stat_fail
			exit
		fi
		
		stat_busy "Starting Wireless Network"

		if [ -n $WIRELESS_MODULE ]; then
			modprobe $WIRELESS_MODULE
		fi

 		$IFCONFIG up
		SCAN=$($IWLIST scan)
		essid_file=$ESSID_LIST

		exec<$essid_file
		   while read line
		   do
			if [[ -n $line && $line != \#* && $(echo $SCAN | grep "ESSID:\"$line\"" | head -n 1 | wc -l) -eq 1 ]] ; then
				ESSID=$line
				$IWCONFIG essid "$ESSID"
		    if [[ $( $IWCONFIG | grep "ESSID:\"$ESSID\"" | wc -l ) -ne 1 ]] ; then
					echo "Unable to associate with \"$ESSID\""
					stat_fail
					exit 1
				fi
				$WPA_SUPPLICANT

				sleep 1

				if [ -z $( $DHCPCD 2> /dev/null | grep "leased \([0-9]\{0,3\}\.\?\)\{4\}") ] ; then
					add_daemon wireless
					echo "Connected to $ESSID"
					stat_done
					exit
				fi

				echo "Unable to get IP address"
				stat_fail
				exit 1
			fi
		   done

		echo "No recognised APs found"
		stat_fail
		exit 1

		;;
	stop)
		if [ $( $IFCONFIG | grep inet | wc -l) != "0" ] ; then
			stat_busy "Stopping Wireless Network"

			if [ -e $DHCPCD_PIDFILE ] ; then
				kill $(cat $DHCPCD_PIDFILE)
			fi

			if [ -e $WPA_SUPPLICANT_PIDFILE ] ; then
				kill $(cat $WPA_SUPPLICANT_PIDFILE)
			fi

			$IFCONFIG down

			if [ -n $WIRELESS_MODULE ]; then
				modprobe -r $WIRELESS_MODULE
			fi
			rm_daemon wireless
			stat_done
			exit
		else
			echo "Wireless Network is not running."
			stat_fail
			exit 1	
		fi

		;;
	restart)
		$0 stop
		sleep 1
		$0 start
		;;
	status)
		if [ $( $IFCONFIG 2> /dev/null | grep inet | wc -l) -ne 0 ] ; then
			IWCONFIG
			IFCONFIG
		else
			echo "Wireless network is not running" >&2
		fi
		;;
	*)
		echo "usage: $0 {start|stop|restart|status}"
		;;
esac

# vim: set ts=2 sw=2 noet:
