#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

if [ -z $WIRELESS_INTERFACE ]; then
	WIRELESS_INTERFACE=wlan0
fi

if [ -z $ESSID_LIST ]; then
	ESSID_LIST=/etc/essids
fi

if [ -z $WPA_SUPPLICANT_CONF ]; then
	WPA_SUPPLICANT_CONF=/etc/wpa_supplicant.conf
fi


case "$1" in
	start)

		if [ $(ifconfig $WIRELESS_INTERFACE 2> /dev/null | grep inet | wc -l) -ne 0 ] ; then
			echo "Wireless Network is already running. Try 'wireless restart'"
			stat_fail
			exit
		fi
		
		stat_busy "Starting Wireless Network"

		if [ -n $WIRELESS_MODULE ]; then
			modprobe $WIRELESS_MODULE
		fi

 		ifconfig $WIRELESS_INTERFACE up
		SCAN=$(iwlist $WIRELESS_INTERFACE scan)
		essid_file=$ESSID_LIST

		exec<$essid_file
		   while read line
		   do
			if [[ -n $line && $line != \#* && $(echo $SCAN | grep "ESSID:\"$line\"" | head -n 1 | wc -l) -eq 1 ]] ; then
				ESSID=$line
				iwconfig $WIRELESS_INTERFACE essid "$ESSID"
				wpa_supplicant -B -i $WIRELESS_INTERFACE -c $WPA_SUPPLICANT_CONF  -P /var/run/wpa_supplicant-$WIRELESS_INTERFACE.pid

				sleep 1

				if [ -z $(dhcpcd $WIRELESS_INTERFACE 2> /dev/null | grep "leased \([0-9]\{0,3\}\.\?\)\{4\}") ] ; then
					add_daemon wireless
					echo "Connected to $ESSID"
					stat_done
					exit
				fi

				echo "Unable to get IP address"
				stat_fail
				exit 1
			fi
		   done

		echo "No recognised APs found"
		stat_fail
		exit 1

		;;
	stop)
		if [ $(ifconfig $WIRELESS_INTERFACE | grep inet | wc -l) != "0" ] ; then
			stat_busy "Stopping Wireless Network"

			if [ -e /var/run/dhcpcd-$WIRELESS_INTERFACE.pid ] ; then
				kill $(cat /var/run/dhcpcd-$WIRELESS_INTERFACE.pid)
			fi

			if [ -e /var/run/wpa_supplicant-$WIRELESS_INTERFACE.pid ] ; then
				kill $(cat /var/run/wpa_supplicant-$WIRELESS_INTERFACE.pid)
			fi

			ifconfig $WIRELESS_INTERFACE down

			if [ -n $WIRELESS_MODULE ]; then
				modprobe -r $WIRELESS_MODULE
			fi

			rm_daemon wireless
			stat_done
			exit
		else
			echo "Wireless Network is not running."
			stat_fail
			exit 1	
		fi

		;;
	restart)
		$0 stop
		sleep 1
		$0 start
		;;
	status)
		if [ $(ifconfig $WIRELESS_INTERFACE 2> /dev/null | grep inet | wc -l) -ne 0 ] ; then
			iwconfig $WIRELESS_INTERFACE
			ifconfig $WIRELESS_INTERFACE
		else
			echo "Wireless network is not running" >&2
		fi
		;;
	*)
		echo "usage: $0 {start|stop|restart|status}"
		;;
esac

# vim: set ts=2 sw=2 noet:
